version: '3.8'

services:
  streams-prefetcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stremio-streams-prefetcher
    restart: unless-stopped

    ports:
      - "5000:5000"

    volumes:
      # Persist configuration, database, and logs
      - ./data:/app/data

    environment:
      - PORT=5000
      - TZ=UTC

    labels:
      # Traefik labels for reverse proxy (uncomment and configure as needed)
      # - "traefik.enable=true"
      # - "traefik.http.routers.streams-prefetcher.rule=Host(`streams-prefetcher.yourdomain.com`)"
      # - "traefik.http.routers.streams-prefetcher.entrypoints=websecure"
      # - "traefik.http.routers.streams-prefetcher.tls=true"
      # - "traefik.http.routers.streams-prefetcher.tls.certresolver=letsencrypt"
      # - "traefik.http.services.streams-prefetcher.loadbalancer.server.port=5000"

    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Resource limits (adjust as needed)
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M

networks:
  default:
    name: stremio-prefetcher-network
